name: Deploy to Docker Hub
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] #docker not supported on macOS for GAction
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

        
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: use npm to install newman
      run: |
        npm install newman
           
#     - name: newman run
#       run: |
#         newman run https://api.postman.com/collections/26096184-380b125a-a6a3-46f6-a617-f342637f9228?access_key=PMAT-01H00644DM66D8E6X53290YGRC
    
    - name: Build and tag Docker image
      run: |
        docker build -t jerrywise97/period-app:Latest .
    
    - name: Log in to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Push Docker image to Docker Hub
      run: |
        docker push jerrywise97/period-app:Latest
        
    - name: Use docker to login into heroku
      run: |
        docker login --username=_ --password=0d8ea88b-721d-4411-86a2-15a7b48271a6 registry.heroku.com
        
#   - name: docker push to heroku 
   # docker build -t registry.heroku.com/gatest/web .
   # docker push registry.heroku.com/gatest/web
   
    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.12.12
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
       # Email that you use with heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
      # The appname to use for deploying/updating
        heroku_app_name: ${{secrets.HEROKU_APP}}
        
        
     

        
  #     - name: Cleanup pre-installed tools
#       run: |
#         # This is a fix for https://github.com/actions/virtual-environments/issues/1918
#         sudo rm -rf /usr/share/dotnet
#         sudo rm -rf /opt/ghc
#         sudo rm -rf "/usr/local/share/boost"
#         sudo rm -rf "$AGENT_TOOLSDIRECTORY"





#     - name: Publish to Docker Hub
#       uses: docker/build-push-action@v1     
#       with:       
#         username: ${{ secrets.DOCKER_HUB_USERNAME }} 
#         password:  ${{ secrets.DOCKER_HUB_PASSWORD }}
#         repository: jerrywise97/period-app
