name: Deploy to heroku
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      #heroku already have there ci/cd tool that do all this things for us not like we are running regression so i dont think we need an action in the dev branch
      #what we can do is to run the QA excutable file 
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: push heroku
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        
#     - name: Install Heroku CLI
#       run: curl https://cli-assets.heroku.com/install.sh | sh

#     - name: Log in to Heroku
#       run: heroku login -i

#     - name: Set up Heroku Git remote
#       run: heroku git:remote -a ${{secrets.HEROKU_APP_NAME}}

#     - name: Push to Heroku
#       run: git push heroku dev
        
    - name: use npm to install newman
      run: |
        npm install newman
