name: Deploy to heroku
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  
jobs:
  ubuntu-jobs:
   runs-on: ubuntu-latest
   
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      #heroku already have there ci/cd tool that do all this things for us not like we are running regression so i dont think we need an action in the dev branch
      #what we can do is to run the QA excutable file 
      
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: use npm to install newman
      run: |
        npm install newman
        
    - name: newman run
      run: |
        newman run https://api.postman.com/collections/26096184-380b125a-a6a3-46f6-a617-f342637f9228?access_key=PMAT-01H00644DM66D8E6X53290YGRC
    
           
